In [2]:
import numpy as np

In [3]:
d=np.array([11,23,13,32,9,30,11,31,11,31,8,24,10,22,10,24,7,20,8,25,-13,30,12,24,9,24,11,32,15,26,14,31,12,28,12,31,15,20,13,25,6,23,13,26,12,21,11,30,7,23,9,24,6,29,10,26,10,20,8,32,13,32,13,24,11,21,6,25,11,31,15,28,11,24,12,24,10,30,9,28,14,20,7,21,7,22,10,28,6,20,10,30,13,22,14,26,8,23,6,20,12,25,10,27,6,25,6,27,12,31,8,32,4,20,7,22,8,19,7,22,4,19,3,2,22,4,4,22,2,18,4,19,8,22,7,20,8,6,20,3,8,22,4,18,8,18,7,18,4,20,5,3,21,7,5,21,5,21,3,18,7,22,5,19,7,5,19,7,11,19,8,18,-10,21,9,19,7,18,12,71,20,11,9,22,9,18,9,19,10,21,8,18,12,10,18,9,11,18,10,19,10,19,10,20,9,21,12,8,22,11,8,18,7,21,9,18,9,20,10,20,11,10,21,11])

In [4]:
d.shape

(224,)

In [5]:
x=np.reshape(d,(4,4,7,2))

In [6]:
x.shape

(4, 4, 7, 2)

In [7]:
x.ndim

4

In [8]:
print(x)

[[[[ 11  23]
   [ 13  32]
   [  9  30]
   [ 11  31]
   [ 11  31]
   [  8  24]
   [ 10  22]]

  [[ 10  24]
   [  7  20]
   [  8  25]
   [-13  30]
   [ 12  24]
   [  9  24]
   [ 11  32]]

  [[ 15  26]
   [ 14  31]
   [ 12  28]
   [ 12  31]
   [ 15  20]
   [ 13  25]
   [  6  23]]

  [[ 13  26]
   [ 12  21]
   [ 11  30]
   [  7  23]
   [  9  24]
   [  6  29]
   [ 10  26]]]


 [[[ 10  20]
   [  8  32]
   [ 13  32]
   [ 13  24]
   [ 11  21]
   [  6  25]
   [ 11  31]]

  [[ 15  28]
   [ 11  24]
   [ 12  24]
   [ 10  30]
   [  9  28]
   [ 14  20]
   [  7  21]]

  [[  7  22]
   [ 10  28]
   [  6  20]
   [ 10  30]
   [ 13  22]
   [ 14  26]
   [  8  23]]

  [[  6  20]
   [ 12  25]
   [ 10  27]
   [  6  25]
   [  6  27]
   [ 12  31]
   [  8  32]]]


 [[[  4  20]
   [  7  22]
   [  8  19]
   [  7  22]
   [  4  19]
   [  3   2]
   [ 22   4]]

  [[  4  22]
   [  2  18]
   [  4  19]
   [  8  22]
   [  7  20]
   [  8   6]
   [ 20   3]]

  [[  8  22]
   [  4  18]
   [  8  18]
   [  7  18]
   [  4  20]
 

In [9]:
print(x[0:4,0]) #daily temperature for the first week of each month

[[[ 11  23]
  [ 13  32]
  [  9  30]
  [ 11  31]
  [ 11  31]
  [  8  24]
  [ 10  22]]

 [[ 10  20]
  [  8  32]
  [ 13  32]
  [ 13  24]
  [ 11  21]
  [  6  25]
  [ 11  31]]

 [[  4  20]
  [  7  22]
  [  8  19]
  [  7  22]
  [  4  19]
  [  3   2]
  [ 22   4]]

 [[ 11  19]
  [  8  18]
  [-10  21]
  [  9  19]
  [  7  18]
  [ 12  71]
  [ 20  11]]]


In [10]:
print(x[0:4,0:7,1]) #4tuesday temperature of each month

[[[13 32]
  [ 7 20]
  [14 31]
  [12 21]]

 [[ 8 32]
  [11 24]
  [10 28]
  [12 25]]

 [[ 7 22]
  [ 2 18]
  [ 4 18]
  [ 5 21]]

 [[ 8 18]
  [ 9 18]
  [10 19]
  [ 7 21]]]


In [11]:
x

array([[[[ 11,  23],
         [ 13,  32],
         [  9,  30],
         [ 11,  31],
         [ 11,  31],
         [  8,  24],
         [ 10,  22]],

        [[ 10,  24],
         [  7,  20],
         [  8,  25],
         [-13,  30],
         [ 12,  24],
         [  9,  24],
         [ 11,  32]],

        [[ 15,  26],
         [ 14,  31],
         [ 12,  28],
         [ 12,  31],
         [ 15,  20],
         [ 13,  25],
         [  6,  23]],

        [[ 13,  26],
         [ 12,  21],
         [ 11,  30],
         [  7,  23],
         [  9,  24],
         [  6,  29],
         [ 10,  26]]],


       [[[ 10,  20],
         [  8,  32],
         [ 13,  32],
         [ 13,  24],
         [ 11,  21],
         [  6,  25],
         [ 11,  31]],

        [[ 15,  28],
         [ 11,  24],
         [ 12,  24],
         [ 10,  30],
         [  9,  28],
         [ 14,  20],
         [  7,  21]],

        [[  7,  22],
         [ 10,  28],
         [  6,  20],
         [ 10,  30],
         [ 13,  22],

In [12]:
print(x[1:4:2,0:4,0:7,1]) #5max temp for all w d of dec and feb

[[[20 32 32 24 21 25 31]
  [28 24 24 30 28 20 21]
  [22 28 20 30 22 26 23]
  [20 25 27 25 27 31 32]]

 [[19 18 21 19 18 71 11]
  [22 18 19 21 18 10  9]
  [18 19 19 20 21  8 11]
  [18 21 18 20 20 10 11]]]


In [38]:
#6 nov less than 8
for i in range(0,4):
    y=x[0,i:i+1,0:7,0]
    z=x[0,i:i+1,0:7,0]<8
    print("week number:",i+1)
    print(y[z])

week number: 1
[]
week number: 2
[  7 -13]
week number: 3
[6]
week number: 4
[7 6]


In [14]:
z=x[0,0:4,0:7,0]<8

In [15]:
print(y[z]) #nov less than 8

[  7 -13   6   7   6]


In [16]:
k=x[1:3,0:4,0:7,1] #7dec and jan temp greater then 20

In [17]:
l=x[1:3,0:4,0:7,1]>20

In [18]:
print(k[l])

[32 32 24 21 25 31 28 24 24 30 28 21 22 28 30 22 26 23 25 27 25 27 31 32
 22 22 22 22 22 21 21 22]


In [19]:
s=np.mean(x[2:4,0:4,0:7,1]) #12. ang max temp for all winter months in jaipur

In [20]:
print(s)

17.232142857142858


In [21]:
print(np.mean(x[1])) #13 min avg temp dec months

17.785714285714285


In [22]:
print(np.mean(x[1:3])) #14 avg temp for dec and jan

14.723214285714286


In [23]:
a=np.mean(x[0,0:4,0:7,1]) #17 nov below avg 

In [24]:
b=x[0,0:4,0:7,1]

In [25]:
c=b<a

In [26]:
print(np.shape(b[c]))

(17,)
